### PR TITLE
Number Guessing Game program Added

### PR DESCRIPTION
**Pull request by Mudassir97**
This Java program is a classic number guessing game. The computer generates a random number between 1 and 100, and the player has to guess it. The program provides feedback to the player, indicating whether their guess is too high or too low. The game continues until the player guesses the correct number. Try your luck and see how many attempts it takes you to crack the code!

### CODE REVIEW

**Comment by Mudassir97** [comment]
repository excluded

**Comment by whitedevil9911** [comment]
sorry for that IDK also just u can go to the other repo IDK

**Comment by whitedevil9911** [comment]
https://github.com/hari7261/Hacktoberfest-2024   u can done your repo into this 
i think it will work on your Hacktoberfest 24

**Comment by whitedevil9911** [comment]
My HackToberfest 24 Account is also Excluded

**Pull request merged**
